Fix: VideoCarousel.tsx type error
The error `src/components/landing/VideoCarousel.tsx(203,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates an issue with how the `<style jsx>` tag is being used.  This commit will remove the `jsx: true` property from the style tag.